### PR TITLE
add latest maven 3.8.3

### PR DESCRIPTION
**Pull request by longtimeago**
part of https://github.com/Proemion/ts2-psp-merge/issues/28086

### CODE REVIEW

**Comment by longtimeago** [comment]
@gkranis Could you merge, please?

**Comment by longtimeago** [comment]
@unicolet please )

**Review by unicolet — APPROVED** [review]
@longtimeago thanks!

**Comment by longtimeago** [comment]
@unicolet worth adding more maintainers here?

**Comment by unicolet** [comment]
@longtimeago sure, done :-) Of course Proemion org admins can change that at any time

**Comment by longtimeago** [comment]
@unicolet thank you :)

**Pull request merged**
