### PR TITLE
Fix env path

### PR DESCRIPTION
**Pull request by A-Helberg**

### CODE REVIEW

**Comment by rafaph** [comment]
Hello, @unicolet, any chance to merge this?

**Comment by unicolet** [comment]
@rafaph TBH I'm not sure. on Ubuntu env is under both locations (`/usr/bin/env` and `/bin/env`) so I don't see a reason to apply the change. Perhaps you could help me understand why I should merge this change?

**Comment by man8** [comment]
@unicolet At least two systems that I checked quickly don't have `/bin/env`, only `/usr/bin/env`:

1. MacOS (Ventura 13.4.1 (c))
2. Alpine Linux (3.18.2)

**Comment by unicolet** [comment]
I verified and `/bin/env` is only present in my system (fresh ubuntu 22.04 install), but not on other ubuntu systems. There the default is `/usr/bin/env`. Therefore I'll merge. Thanks for the PR and the reminder :)

**Pull request merged**
